import prettier from 'eslint-config-prettier';
import path from 'node:path';
import js from '@eslint/js';
import betterTailwind from 'eslint-plugin-better-tailwindcss';
import svelte from 'eslint-plugin-svelte';
import { defineConfig, includeIgnoreFile } from 'eslint/config';
import globals from 'globals';
import ts from 'typescript-eslint';

const gitignorePath = path.resolve(import.meta.dirname, '.gitignore');

export default defineConfig(
	includeIgnoreFile(gitignorePath),
	// generated by `wrangler types`; regenerated on every `pnpm gen`
	{ ignores: ['worker-configuration.d.ts'] },
	js.configs.recommended,
	ts.configs.recommended,
	svelte.configs.recommended,
	prettier,
	svelte.configs.prettier,
	{
		languageOptions: { globals: { ...globals.browser, ...globals.node } },
		rules: {
			// typescript-eslint strongly recommend that you do not use the no-undef lint rule on TypeScript projects.
			// see: https://typescript-eslint.io/troubleshooting/faqs/eslint/#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors
			'no-undef': 'off'
		}
	},
	{
		files: ['**/*.svelte', '**/*.svelte.ts', '**/*.svelte.js'],
		languageOptions: {
			parserOptions: {
				projectService: true,
				extraFileExtensions: ['.svelte'],
				parser: ts.parser
			}
		}
	},
	{
		files: ['**/*.svelte', '**/*.svelte.ts', '**/*.svelte.js', '**/*.ts'],
		extends: [betterTailwind.configs['recommended-error']],
		settings: {
			'better-tailwindcss': {
				// Tailwind v4 has no config file; the stylesheet is the source of truth.
				entryPoint: 'src/routes/layout.css'
			}
		},
		rules: {
			// prettier-plugin-tailwindcss already owns class order and wrapping.
			'better-tailwindcss/enforce-consistent-class-order': 'off',
			'better-tailwindcss/enforce-consistent-line-wrapping': 'off',
			// The design-language classes in layout.css are hand-written CSS, not
			// utilities, so Tailwind cannot know them.
			'better-tailwindcss/no-unknown-classes': [
				'error',
				{
					ignore: [
						'^mat-(panel|float|well|cap|row)$',
						'^(press|meta|tnum|fade-y|no-bar|scroll-inset)$',
						'^shiki$'
					]
				}
			]
		}
	}
);
